Fix: missing documentation for a struct on `#![deny(missing_docs)]`  (#186)
* fix: add #[doc] to ssa structs and fields; close https://github.com/Artisan-Lab/RAPx/issues/184

error: missing documentation for a struct
  |
note: the lint level is defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(missing_docs)]
  |         ^^^^^^^^^^^^

error: missing documentation for a struct field
  |
note: the lint level is defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(missing_docs)]
  |         ^^^^^^^^^^^^

* add deny_missing_docs testcase

cc https://github.com/Artisan-Lab/RAPx/issues/184

* batch.sh: test support/deny_missing_docs